### ISSUE TITLE
Identity PFX

### ISSUE THREAD

**Issue by elielam** [mcfedr/bitwarden-chart#6]
Hello,

First thank you for your Chart.
I want to know what I need to supply to the identity.pfx value ?

I generate a key with openssl and I give it a password but what does I need to fill in this value ? path to file or decripted cert ?
Also I use custom nginx and ingress route will this have an impact on that ? (I don't really understand the purpose of identity container)

Sorry for my poor english.

Thank you in advance.

**Comment by elielam** [comment]
I finnaly found my answer, I let this here for other.

If you use your own nginx and cert-manager with lets encrypt, firstly change in values.yaml nginx service type to ClusterIP and disabled Ingress.
Don't forget to add the identity certificatePassword, you can let pfx empty.
After that launch helm install.

> Apply your ingress and wait until cert manager have create your secret, in my case bitwarden-tls.

> Delete auto created bitwarden-identity (or nameOverride-identity) secret with :

```
kubectl -n bitwarden delete secret bitwarden-identity
```

> Retrieve tls.crt and tls.key

```
kubectl get secret -n bitwarden bitwarden-tls -o go-template='\n{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
```

> Copy retrieved content in identity.crt and indentity.key

> Create identity.pfx based on this two newly created files (don't forget to replace yourCertificatePassword with the value you set in values.yml)

```
openssl pkcs12 -export -out identity.pfx -inkey identity.key -in identity.crt -certfile identity.crt -passout pass:<yourCertificatePassword>
```

> Create secret with this command (don't forget to replace yourCertificatePassword with the value you set in values.yml)

```
kubectl -n bitwarden create secret generic bitwarden-identity --from-file=identity.pfx=./identity.pfx --from-literal=certificate-password=<yourCertificatePassword>
```

Reopen if you someone need help !

**Comment by mcfedr** [comment]
well done on working that out :) I've certainly really made the chart for my own use, but glad you could use it.

**Comment by jiwanovski87** [comment]
Hey guys @mcfedr @pogossian ,

I am currently facing the issue that I have followed these recommondations but the ```Identity``` Container is still making some trouble with the certificate. 

In the logs of the ```Identity``` I get the following information
```
kubectl --kubeconfig kubeconfig -n vault logs vault-0 identitychown: changing ownership of '/etc/bitwarden/identity/..data': Read-only file system
chown: changing ownership of '/etc/bitwarden/identity/identity.pfx': Read-only file system
chown: changing ownership of '/etc/bitwarden/identity/..2021_11_02_19_13_49.430205126/identity.pfx': Read-only file system
chown: changing ownership of '/etc/bitwarden/identity/..2021_11_02_19_13_49.430205126': Read-only file system
chown: changing ownership of '/etc/bitwarden/identity': Read-only file system
Unhandled exception. System.Exception: No identity certificate to use.
   at Bit.Core.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IWebHostEnvironment env, GlobalSettings globalSettings) in /home/appveyor/projects/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 384
   at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/server/src/Identity/Startup.cs:line 63
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bit.Identity.Program.Main(String[] args) in /home/appveyor/projects/server/src/Identity/Program.cs:line 13
```
Any idea what is going wrong?
